Repository tigerbeetle/tigerbeetle, pull requests merged in 2024-12, with the labels that each got.

#2520 lsm: assert that CacheMap is exclusive
  src/lsm/cache_map.zig
Labels: fuzz lsm_cache_map, fuzz vopr_lite

#2544 LSM/Scan: Fix missing intersection results bug
  src/fuzz_tests.zig
  src/lsm/scan_fuzz.zig
  src/lsm/scan_merge.zig
  src/lsm/scan_tree.zig
  src/state_machine.zig
  src/state_machine/auditor.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite, fuzz vopr, fuzz lsm_scan

#2557 VSR: Improve `prepare_timeout`/`replicate` replica selection
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2511 vopr: implement pauses
  src/testing/cluster.zig
  src/vopr.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite

#2577 vsr: assert against ABA problem during commit
  src/vsr/journal.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2582 VSR: Timeout backoff is too aggressive
  src/vsr.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite

#2584 vsr: throttle repair a bit
  src/constants.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite

#2592 LSM: Coalesce tables in memory
  src/lsm/compaction.zig
  src/lsm/forest.zig
  src/lsm/forest_fuzz.zig
  src/lsm/table_memory.zig
  src/lsm/tree.zig
  src/lsm/tree_fuzz.zig
  src/vopr.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite

#2604 Fuzz: Fix fuzz_lsm_scan checkpoint schedule
  src/lsm/scan_fuzz.zig
Labels: fuzz lsm_scan

#2607 vsr: log anomalous behaviour and important state transitions for alerting
  src/clients/c/tb_client/context.zig
  src/config.zig
  src/constants.zig
  src/vsr/client.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2608 replica: broadcast small prepares
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite, fuzz vopr

#2613 vsr: replicate committed messages
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2619 VSR: Fix + clarify sync_content logging
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2593 vsr: repair headers&prepares even when lagging behind the primary
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2623 vsr: optimize the order of repair of prepares
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2625 vsr: always repair if header being repaired has the same view as op_head
  src/vopr.zig
  src/vsr/journal.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2626 vsr: speed up commit during repair
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2627 vsr: relax defense-in-depth for committing
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2628 VSR: Request extra headers during repair
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2624 VOPR: Reduce journal read/write iops
  src/config.zig
Labels: fuzz vopr_lite

#2629 VSR: get rid of awaiting_checkpoint sync state
  src/message_pool.zig
  src/vsr/journal.zig
  src/vsr/replica.zig
  src/vsr/sync.zig
Labels: fuzz vopr_lite, fuzz vopr
