Repository tigerbeetle/tigerbeetle, pull requests merged in 2024-07, with the labels that each got.

#2035 LSM/Manifest: Lift compaction_table table count assert
  src/lsm/manifest.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite

#2042 LSM/Manifest: Assert overlapping table counts
  CHANGELOG.md
  src/lsm/manifest.zig
  src/lsm/manifest_level.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite

#2069 LSM/Compaction: Assert data_block_empty at beat start
  src/lsm/compaction.zig
Labels: fuzz lsm_tree, fuzz lsm_forest

#2070 LSM: Greedy level-0 table coalescing
  src/config.zig
  src/constants.zig
  src/lsm/compaction.zig
  src/lsm/manifest.zig
  src/lsm/manifest_level.zig
  src/lsm/table_memory.zig
  src/stdx/bounded_array.zig
  src/unit_tests.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite

#2117 Fix incorrect `timestamp_max` max value.
  docs/reference/account-filter.md
  docs/reference/requests/create_transfers.md
  src/lsm/forest_fuzz.zig
  src/lsm/groove.zig
  src/lsm/timestamp_range.zig
  src/state_machine.zig
Labels: fuzz vopr_lite

#2120 Fix `pulse` in idle clusters.
  src/clients/dotnet/TigerBeetle.Tests/IntegrationTests.cs
  src/clients/java/src/test/java/com/tigerbeetle/IntegrationTest.java
  src/clients/node/src/test.ts
  src/state_machine.zig
  src/testing/state_machine.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2137 vsr: don't overwrite ops from previous WAL unless they're durable on a commit-quorum of checkpoints
  src/constants.zig
  src/vsr.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite, fuzz vopr

#2139 vsr: don't block commit on repairing ops from the past checkpoint
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2154 VSR: `Header.Reply.peer_type=unknown`; test `peer_type`
  src/testing/cluster/network.zig
  src/vsr/message_header.zig
Labels: fuzz vopr_lite

#2143 vsr: decoupling replication and appending to WAL
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2153 VSR: Fix stuck-client bug; Add eviction replica_tests (part 1/2)
  src/aof.zig
  src/clients/c/tb_client/context.zig
  src/clients/c/tb_client/echo_client.zig
  src/repl.zig
  src/testing/cluster.zig
  src/testing/cluster/state_checker.zig
  src/tigerbeetle/benchmark_load.zig
  src/vsr/client.zig
  src/vsr/message_header.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite
