Repository tigerbeetle/tigerbeetle, pull requests merged in 2024-08, with the labels that each got.

#2175 StateMachine: Fix balancing transfers with large balances
  src/state_machine.zig
Labels: bug, fuzz vopr_lite

#2174 Test/VOPR: Test client eviction in the VOPR (2/2)
  src/testing/cluster.zig
  src/testing/reply_sequence.zig
  src/vopr.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite

#2200 LSM: Don't call `iterator.empty()` of undefined iterator
  src/lsm/scan_tree.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite, fuzz lsm_scan

#2212 vsr: remove old state sync dead code
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2207 vsr: state sync performance improvements
  src/config.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2211 vsr: ignore messages related to the old state sync protocol
  src/vsr/replica.zig
Labels: fuzz vopr

#2171 Import historical events
  docs/reference/account.md
  docs/reference/requests/create_accounts.md
  docs/reference/requests/create_transfers.md
  docs/reference/transfer.md
  src/clients/c/tb_client.h
  src/clients/c/tb_client/context.zig
  src/clients/dotnet/README.md
  src/clients/dotnet/TigerBeetle.Tests/IntegrationTests.cs
  src/clients/dotnet/TigerBeetle/Bindings.cs
  src/clients/dotnet/dotnet_bindings.zig
  src/clients/dotnet/samples/walkthrough/Program.cs
  src/clients/go/README.md
  src/clients/go/pkg/native/tb_client.h
  src/clients/go/pkg/types/bindings.go
  src/clients/go/samples/walkthrough/main.go
  src/clients/go/tb_client_test.go
  src/clients/java/README.md
  src/clients/java/java_bindings.zig
  src/clients/java/samples/walkthrough/src/main/java/Main.java
  src/clients/java/src/main/java/com/tigerbeetle/AccountBatch.java
  src/clients/java/src/main/java/com/tigerbeetle/AccountFlags.java
  src/clients/java/src/main/java/com/tigerbeetle/CreateAccountResult.java
  src/clients/java/src/main/java/com/tigerbeetle/CreateTransferResult.java
  src/clients/java/src/main/java/com/tigerbeetle/InitializationStatus.java
  src/clients/java/src/main/java/com/tigerbeetle/PacketStatus.java
  src/clients/java/src/main/java/com/tigerbeetle/TransferBatch.java
  src/clients/java/src/main/java/com/tigerbeetle/TransferFlags.java
  src/clients/java/src/test/java/com/tigerbeetle/AsyncRequestTest.java
  src/clients/java/src/test/java/com/tigerbeetle/BlockingRequestTest.java
  src/clients/java/src/test/java/com/tigerbeetle/CreateAccountResultTest.java
  src/clients/java/src/test/java/com/tigerbeetle/CreateTransferResultTest.java
  src/clients/java/src/test/java/com/tigerbeetle/IntegrationTest.java
  src/clients/node/README.md
  src/clients/node/samples/walkthrough/main.js
  src/clients/node/src/bindings.ts
  src/clients/node/src/test.ts
  src/lsm/forest_fuzz.zig
  src/lsm/groove.zig
  src/lsm/tree.zig
  src/repl.zig
  src/scripts/client_readmes.zig
  src/state_machine.zig
  src/state_machine/workload.zig
  src/tigerbeetle.zig
  src/tigerbeetle/benchmark_load.zig
  src/tigerbeetle/cli.zig
Labels: fuzz lsm_forest, fuzz vopr_lite

#2221 vsr: syncing replicas shouldn't falsely contribute to checkpoint durability
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2237 StateMachine: Use `AMOUNT_MAX` as post-pending sentinel
  docs/coding/two-phase-transfers.md
  docs/reference/requests/create_transfers.md
  docs/reference/transfer.md
  src/state_machine.zig
Labels: fuzz vopr_lite

#2238 LSM: Optionally index zero values
  src/lsm/groove.zig
  src/lsm/scan_fuzz.zig
  src/state_machine.zig
  src/testing/state_machine.zig
Labels: fuzz lsm_forest, fuzz vopr_lite, fuzz lsm_scan

#2240 LSM: Secondary indexes on flags.
  build.zig
  src/lsm/composite_key.zig
  src/lsm/forest_fuzz.zig
  src/lsm/groove.zig
  src/state_machine.zig
  src/stdx.zig
  src/tigerbeetle/inspect.zig
Labels: fuzz lsm_forest, fuzz vopr_lite

#2255 vsr: prefer wal repair over state sync
  src/testing/marks.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr

#2253 vsr: primary rejects prepares if log_view is not durable
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2252 Change `init` signature
  build.zig
  docs/TIGER_STYLE.md
  src/lsm/compaction.zig
  src/lsm/forest.zig
  src/lsm/forest_fuzz.zig
  src/lsm/groove.zig
  src/lsm/manifest.zig
  src/lsm/manifest_level.zig
  src/lsm/manifest_level_fuzz.zig
  src/lsm/manifest_log.zig
  src/lsm/manifest_log_fuzz.zig
  src/lsm/node_pool.zig
  src/lsm/scan_buffer.zig
  src/lsm/scan_builder.zig
  src/lsm/scan_fuzz.zig
  src/lsm/segmented_array.zig
  src/lsm/segmented_array_benchmark.zig
  src/lsm/table_memory.zig
  src/lsm/tree.zig
  src/lsm/tree_fuzz.zig
  src/state_machine.zig
  src/testing/state_machine.zig
  src/vsr/replica.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite, fuzz lsm_manifest_log, fuzz lsm_scan

#2257 vsr: correct assert
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2234 Closing accounts
  docs/coding/recipes/close-account.md
  docs/reference/account.md
  docs/reference/requests/create_transfers.md
  docs/reference/transfer.md
  src/clients/c/tb_client.h
  src/clients/dotnet/TigerBeetle.Tests/IntegrationTests.cs
  src/clients/dotnet/TigerBeetle/Bindings.cs
  src/clients/go/pkg/native/tb_client.h
  src/clients/go/pkg/types/bindings.go
  src/clients/go/tb_client_test.go
  src/clients/java/src/main/java/com/tigerbeetle/AccountFlags.java
  src/clients/java/src/main/java/com/tigerbeetle/CreateTransferResult.java
  src/clients/java/src/main/java/com/tigerbeetle/TransferFlags.java
  src/clients/java/src/test/java/com/tigerbeetle/IntegrationTest.java
  src/clients/node/src/bindings.ts
  src/clients/node/src/test.ts
  src/lsm/forest_fuzz.zig
  src/state_machine.zig
  src/stdx.zig
  src/tigerbeetle.zig
Labels: fuzz lsm_forest
