Repository tigerbeetle/tigerbeetle, pull requests merged in 2024-11, with the labels that each got.

#2444 vsr: handle inflight write for old reply post state sync
  src/vsr/client_replies.zig
Labels: fuzz vopr_lite, fuzz vopr

#2443 lsm: compaction comments and assertions
  src/lsm/compaction.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite

#2437 grid: divide request buffer between the read_global_queue & faulty_blocks queues
  src/vopr.zig
  src/vsr/grid.zig
  src/vsr/grid_blocks_missing.zig
Labels: fuzz vopr_lite, fuzz vopr

#2461 vsr: on_commit must check hash chain from message.header.commit → self.op
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2475 [StateMachine] Save 256K of RAM by not having a prefetch cache for historical balances.
  src/state_machine.zig
Labels: fuzz vopr_lite

#2506 VSR: Misc misdirected write + client reply fixes
  src/iops.zig
  src/vsr/client_replies.zig
  src/vsr/journal.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2513 LSM/CacheMap: Scoped insert may be evicted into stash
  src/lsm/cache_map.zig
  src/lsm/cache_map_fuzz.zig
  src/lsm/forest_fuzz.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz lsm_cache_map, fuzz vopr_lite

#2517 VSR: Set upgrade quorum size to replica_count
  src/vsr.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite, fuzz vopr

#2522 fix: enforce single-object restrictions for non-sliceable operations & apply TigerStyle
  src/repl.zig
Labels: enhancement
