Repository tigerbeetle/tigerbeetle, pull requests merged in 2024-10, with the labels that each got.

#2363 vsr: potential primaries updating their SV may have gaps in journal
  src/vsr.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2359 LSM: Incrementally sort mutable table
  src/lsm/compaction.zig
  src/lsm/forest.zig
  src/lsm/groove.zig
  src/lsm/table_memory.zig
  src/lsm/tree.zig
  src/lsm/tree_fuzz.zig
  src/trace.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite

#2382 vsr: use checkpoint header from superblock on startup if vsr_headers are from future checkpoint
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2385 vsr: nack different prepares b/w DVC & journal iff DVC is non-blank
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2391 vopr: pass correct op_min to find_latest_headers_break_between in core_missing_prepare
  src/vopr.zig
Labels: fuzz vopr_lite, fuzz vopr

#2402 vsr: fix asserts for start_view update with missing root op
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2399 vsr: DVC header is blank and journal has valid header from old wrap
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite, fuzz vopr

#2409 vopr: core_missing_prepare only checks replicas that have attempted to repair
  src/vopr.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2414 vsr: replica needn't repair its *entire* journal to become primary
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2360 lsm: refactor compaction
  src/constants.zig
  src/iops.zig
  src/lsm/compaction.zig
  src/lsm/forest.zig
  src/lsm/manifest.zig
  src/lsm/tree.zig
  src/lsm/tree_fuzz.zig
  src/ring_buffer.zig
  src/trace.zig
  src/vsr/replica_test.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vopr_lite, fuzz vopr, fuzz lsm_scan

#2416 vsr: send start_view message as soon as you can construct start_view headers
  src/vsr/message_header.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
Labels: fuzz vopr_lite, fuzz vopr

#2432 vsr: assert free set consistency
  src/lsm/manifest_log.zig
  src/lsm/tree.zig
  src/testing/cluster.zig
  src/testing/cluster/storage_checker.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr
