Repository tigerbeetle/tigerbeetle, pull requests merged in 2025-01, with the labels that each got.

#2635 replica: add in star replication and closed loop replication
  src/tigerbeetle/cli.zig
  src/tigerbeetle/main.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2637 vopr: fix multiple false positives
  src/vopr.zig
Labels: fuzz vopr_lite, fuzz vopr

#2583 VSR: Set timeout RTTs dynamically
  src/aof.zig
  src/clients/c/tb_client.zig
  src/clients/c/tb_client/context.zig
  src/clients/c/tb_client/echo_client.zig
  src/config.zig
  src/constants.zig
  src/repl.zig
  src/testing/cluster.zig
  src/tigerbeetle/benchmark_load.zig
  src/tigerbeetle/main.zig
  src/vsr.zig
  src/vsr/client.zig
  src/vsr/clock.zig
  src/vsr/message_header.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2646 vopr: smallest_missing_prepare_between called with invalid input
  src/vopr.zig
Labels: fuzz vopr_lite, fuzz vopr

#2654 vopr: state checker checks for truncated ops in the WAL
  src/testing/cluster/state_checker.zig
  src/vopr.zig
Labels: fuzz vopr_lite, fuzz vopr

#2662 vsr: rollout new CheckpointState format, stage 0
  src/docs_website/src/docs.zig
  src/vsr.zig
  src/vsr/message_header.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2655 vsr: reduce minimal backoff delay
  src/config.zig
Labels: fuzz vopr_lite, fuzz vopr

#2653 Journal: Don't write invalid redundant headers during repair
  src/testing/cluster.zig
  src/testing/cluster/journal_checker.zig
  src/vsr/journal.zig
Labels: fuzz vopr_lite, fuzz vopr

#2666 VSR/Journal: `writing() → enum{none,slot,exact}`
  src/vsr/journal.zig
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr

#2600 vsr: free grid blocks when checkpoint becomes durable
  src/constants.zig
  src/lsm/compaction.zig
  src/lsm/forest.zig
  src/lsm/forest_fuzz.zig
  src/lsm/manifest_log.zig
  src/lsm/manifest_log_fuzz.zig
  src/lsm/scan_fuzz.zig
  src/lsm/tree_fuzz.zig
  src/message_pool.zig
  src/state_machine.zig
  src/testing/cluster/grid_checker.zig
  src/testing/cluster/storage_checker.zig
  src/testing/vortex/workload.zig
  src/tigerbeetle/inspect.zig
  src/vopr.zig
  src/vsr.zig
  src/vsr/checkpoint_trailer.zig
  src/vsr/free_set.zig
  src/vsr/free_set_fuzz.zig
  src/vsr/grid.zig
  src/vsr/grid_blocks_missing.zig
  src/vsr/grid_scrubber.zig
  src/vsr/message_header.zig
  src/vsr/replica.zig
  src/vsr/replica_test.zig
  src/vsr/superblock.zig
  src/vsr/superblock_fuzz.zig
  src/vsr/superblock_quorums_fuzz.zig
Labels: fuzz lsm_tree, fuzz lsm_forest, fuzz vsr_free_set, fuzz vopr_lite, fuzz vopr, fuzz lsm_manifest_log

#2681 VSR/Grid: Remove invalid zero-padding assert
  src/message_bus.zig
  src/testing/cluster/network.zig
  src/testing/storage.zig
  src/vsr/grid.zig
  src/vsr/journal.zig
  src/vsr/superblock.zig
  src/vsr/superblock_quorums_fuzz.zig
Labels: fuzz vopr_lite, fuzz vopr

#2656 vsr: check some more invariants
  src/vsr/replica.zig
Labels: fuzz vopr_lite

#2692 vsr: send withheld prepare_oks after syncing tables
  src/vsr/replica.zig
Labels: fuzz vopr_lite, fuzz vopr
